spring:
  application:
    name: openfeign-starter

server:
  port: 7070

feign:
  client:
    config:
      default:
        connectionTimeout: 10000
        readTimeout: 10000
        loggerLevel: basic